### ISSUE TITLE
Can you add xps13 9360 i7-7560u(Iris plus 640) support?

### ISSUE THREAD

**Issue by hoanX** [ZombieTheBest/XPS9350-10.13-HighSierra#1]
My computer is always unable to wake up on sleep

**Comment by ZombieTheBest** [comment]
Don't run this script on your XPS 9360. You should follow this LTS guide: https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/

Regarding sleep problem I suggest you to read here and see if everything is patched correctly: https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/

**Comment by ZombieTheBest** [comment]
Closing issue. Feel free to re-open if you need something else!
