### ISSUE TITLE
Is this support apfs？

### ISSUE THREAD

**Issue by ctr54188** [ZombieTheBest/XPS9350-10.13-HighSierra#2]
Syscl deploy don't support 10.13
I saw your link at his github, is this any bugs for 9350 10.13?
my laptop is 9350 3k 6560U,i want try this deploy.sh
thanks

**Comment by ZombieTheBest** [comment]
Right now no bugs. You may experience some Handoff issues tho.

Regarding APFS support just make sure you copy APFS.efi in drivers64 in
your CLOVER folder! Also set FixHeaders_20000000 = true in your config in
case you can't boot High Sierra Installer!

Il 29 Ott 2017 06:52, "ctr54188" <notifications@github.com> ha scritto:

Syscl deploy don't support 10.13
I saw your link at his github, is this any bugs for 9350 10.13?
my laptop is 9350 3k 6560U,i want try this deploy.sh
thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/issues/2>, or mute
the thread

**Comment by x4080** [comment]
Hi, good job for high Sierra, I wondered if I'm currently on Sierra with syscl deploy.sh, to upgrade to high sierra, should I run first your deploy sh then update high sierra 

Or update high sierra first then use your deploy sh?

Sorry for newbie questions

**Comment by ZombieTheBest** [comment]
Update and then use this patched Deploy!

Il 30 Ott 2017 08:37, "x4080" <notifications@github.com> ha scritto:

**Comment by x4080** [comment]
@ZombieTheBest  you're really the best :+1:

**Comment by ctr54188** [comment]
@ZombieTheBest 
i try to install 10.13 yesterday，but it won't boot and show some errors
[http://pan.baidu.com/s/1bzOIYy](url)
[http://pan.baidu.com/s/1geObjDh](url)

**Comment by ZombieTheBest** [comment]
@ctr54188 Please check your links as they are not working.

Did you set FixHeaders_20000000 to true in your config.plist?
Did you placed apfs.efi in your CLOVER/drivers64uefi? 
Have you updated FakeSMC to latest version?

**Comment by ctr54188** [comment]
@ZombieTheBest 

1. yes
2. yes
3. i replace the original CLOVER folder with the one under your Git/XPS9350-macOS/CLOVER

**Comment by vinv** [comment]
I can't boot into the High Sierra installer. I have FixHeaders_20000000 set to true as below in the dsdt section.

			<key>Fixes</key>
			<dict>
				<key>FixHeaders_20000000</key>
				<true/>
			</dict>

And I've disabled SIP (based on something else I saw online) by setting CsrActiveConfig to 0x67.

When I place apfs.efi into my CLOVER/drivers65uefi, it shows a couple of error-like loglines (something about mount points; went by too fast), but still boots fine (into my existing Sierra).

**Comment by ZombieTheBest** [comment]
@vinv Please attach a picture of the error. Links above are not working for me.

**Comment by vinv** [comment]
Sorry about hijacking the thread. It was ctr54188 that had the errors (and the bad links). I don't know if he/she is able to boot into the installer and the install throws errors. But in my case, the installer won't boot at all. It keeps booting right back into my existing Sierra. Does clover capture a boot log? As I wrote, the errors flash by too quickly for me to capture them. Clover continues to boot into my existing Sierra install without issue.

**Comment by vinv** [comment]
I have the latest clover (4268) if that makes any difference.

**Comment by ZombieTheBest** [comment]
@vinv Oh, sorry for that! In Clover press SPACE, select Verbose (-v) and then "Boot with selected options". It should not reboot when a kernel panic appears.

**Comment by vinv** [comment]
There was no kernel panic. It booted fine, but again into Sierra, without going into the install.

**Comment by ctr54188** [comment]
@ZombieTheBest 
you can copy and open the link in a new tab
![20171031122836](https://user-images.githubusercontent.com/26321252/32211513-cc41f30e-be4d-11e7-951d-b44341876895.jpg)
![20171031122816](https://user-images.githubusercontent.com/26321252/32211518-d29ff944-be4d-11e7-99f3-76272af27ddd.jpg)

**Comment by ZombieTheBest** [comment]
Are you trying to update? In that case when you reboot you should find
another boot option in Clover other than the Sierra one

Il 31 Ott 2017 08:06, "vinv" <notifications@github.com> ha scritto:

**Comment by vinv** [comment]
I am trying to update, but no new boot options show up in Clover. After I run the installer, it immediately wants to reboot and the same 3 options show up in Clover (boot default drive, boot Recovery, boot Recovery something else).

**Comment by ZombieTheBest** [comment]
@ctr54188 Please attach your clover folder
@vinv I would create a bootable pendrive and go through the installation.

**Comment by ctr54188** [comment]
@ZombieTheBest 

[CLOVER.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1429884/CLOVER.zip)

**Comment by ZombieTheBest** [comment]
@ctr54188 I don't see any fatal error in that screen. Try to leave only FakeSMC.kext and VoodooPS2Controller.kext in your CLOVER/kexts in USB drive. Also remove SSDT-XHC from ACPI/Patched and try again

**Comment by ctr54188** [comment]
@ZombieTheBest 
![snipaste_2017-10-31_16-17-46](https://user-images.githubusercontent.com/26321252/32213674-22ffb3bc-be57-11e7-9132-8d903f63996f.png)

is this a error?
i will try only FakeSMC.kext and VoodooPS2Controller.kext,thank you

**Comment by vinv** [comment]
@ZombieTheBest Let me know if you'd like me to start another thread (if switching context between ctr54188 and me is difficult).

I loaded the install onto a USB, installed Clover, copied over your CLOVER folder and rebooted to the install media. Install failed almost immediately with a panic in HibernationFixup. Any ideas?

**Comment by ctr54188** [comment]
@ZombieTheBest 
I try to leave only FakeSMC.kext and VoodooPS2Controller.kext , remove SSDT-XHC
it become another error 
i will try once more form first step and make usb installer again
![_20171031163632](https://user-images.githubusercontent.com/26321252/32214404-b072424e-be59-11e7-8fbd-31542fba6c73.jpg)

**Comment by ZombieTheBest** [comment]
@ctr54188 Try to set DropOEM=true on your config.plist

**Comment by ctr54188** [comment]
@ZombieTheBest 
i try make usb install again,the error is same, i think i need install 10.12 have a try
i update BIOS to 1.5.1 a few days ago

**Comment by ZombieTheBest** [comment]
@ctr54188 try to place your current SSDTs + DSDT in ACPI/patched inside ACPI/patched in your USB
