### ISSUE TITLE
F11/F12 does not adjust brightness

### ISSUE THREAD

**Issue by hgh741** [ZombieTheBest/XPS9350-10.13-HighSierra#20]
hi, i replace clover and has been executed Deploy.sh, but F11/F12 does not adjust brightness .
hope to get your reply！ths

**Comment by mircoianese** [comment]
Have you used last Deploy?

Il 06 Gen 2018 3:47 PM, "hgh741" <notifications@github.com> ha scritto:

**Comment by hgh741** [comment]
yes, i am clone https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra.git
my system is 10.12.6

**Comment by mircoianese** [comment]
Please attach your clover folder and Deploy.sh -d output

Il 07 Gen 2018 02:55, "hgh741" <notifications@github.com> ha scritto:

**Comment by hgh741** [comment]
hi, I use syscl's Deploy.sh is work.
thanks
