### ISSUE TITLE
[Solved] Unable to boot into High Sierra after (successful?) install

### ISSUE THREAD

**Issue by ggctseng** [ZombieTheBest/XPS9350-10.13-HighSierra#21]
**2018-02-01**

I'm directing people to this who have problems booting into High Sierra installer to look for my post below.  Do a search for "THIS IS THE SOLUTION REFERENCED IN MY FIRST POST" (searching for the word "solution" would probably work as well).  Please start a new thread where appropriate (i.e., do not ADD to this thread as I won't be checking it).

2018-01-17 1:52pm PST

Resolved one issue, which was I didn't add FixHeaders_20000000 correctly (should be added as a boolean value).  However, the system just reboots after a few screens of logs.  I'll update with more information once I'm able to capture a video.

Please ignore anything beyond this point and go to the 2nd post (1st response) to see my question.

--------------------
I can't seem to run the installer.  The last thing I have tried, after reading the other reported issues, is
 
- removing all kexts except VoodooPS2 and FakeSMC
- added FixHeaders_20000000 to ACPI/DSDT/Fixes/ in plist
- removed SSDT-XHC.aml from ACPI patched.

I used the plist from the git but removed all the IONVMeFamily patches under KextsToPatch based on this thread:

[wmchris fix](https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/4k_sector.md)

I'm not sure what to try next. 

Attached is my CLOVER directory and a picture of the last screen when I try to run the installer.  Lots of text scrolling by... I also attached a screenshot of what I see right as clover is booting up (I note I was actually able to go through the first phase of the installer using the sysctl version, but I was hitting an error and so I tried to reinstall using your files.

![img_9406](https://user-images.githubusercontent.com/9076368/35018078-c1b1246e-fad4-11e7-8ac1-0ff3743625dd.JPG)
![img_9415](https://user-images.githubusercontent.com/9076368/35017732-0dd0afd8-fad3-11e7-8711-0fc5d6b47110.JPG)
[CLOVER.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1637182/CLOVER.zip)

**Comment by ggctseng** [comment]
I have no idea why the 2nd screenshot is upside down, sorry.

**Comment by ggctseng** [comment]
I started over with the Clover folder from the git with only these two changes:
- added FixHeaders_20000000 (this got rid of the weird error above in the 2nd screen shot).
- removed IONVMeFamily patches

and was able to boot to the installer, formatted the drive as APFS using Disk Utility, and then ran the first install portion. Then rebooted and ran the second install portion, so it looked like the install finished.

However, when trying to boot into macOS right after the second install portion, the system restarts.

Here's what I see when I boot into clover, in addition to my USB entry:

- Boot FileVault Prebooter from Preboot
- Boot macOS Install Prebooter from Preboot
- Boot macOS from Macintosh HD
- Boot Recovery from Recovery

Should I see the first 2 entries in clover?  I've tried booting using the first 3 entries, starting with the Boot macOS from Macintosh HD option.  Same results.

I feel I am really close, but stuck and am hoping there's help!

Here's my current CLOVER folder:

[CLOVER.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1641127/CLOVER.zip)

I was able to take a video and put together the boot screens.

![1-2018-01-17-15h19m49s798](https://user-images.githubusercontent.com/9076368/35074186-93f3d742-fba1-11e7-8cb4-f00f437fd85f.png)
![2-2018-01-17-15h20m06s697](https://user-images.githubusercontent.com/9076368/35074187-94181a9e-fba1-11e7-8bc2-0d6f1a54c9df.png)
![3-2018-01-17-15h20m20s956](https://user-images.githubusercontent.com/9076368/35074188-9430d7d2-fba1-11e7-89cf-f7c55bfb20d6.png)
![4-2018-01-17-15h20m56s626](https://user-images.githubusercontent.com/9076368/35074189-9448ed0e-fba1-11e7-94fd-b1a036087bef.png)
![5-2018-01-17-15h21m34s019](https://user-images.githubusercontent.com/9076368/35074190-94649694-fba1-11e7-850e-264fc823b8f3.png)
![6-2018-01-17-15h21m45s851](https://user-images.githubusercontent.com/9076368/35074191-947f6032-fba1-11e7-9530-ced5a8bf363b.png)
![7-2018-01-17-15h22m06s880](https://user-images.githubusercontent.com/9076368/35074192-949853ee-fba1-11e7-90d8-36641befb9ef.png)
![8-2018-01-17-15h22m22s858](https://user-images.githubusercontent.com/9076368/35074193-94b36c10-fba1-11e7-989d-b03b3cc469c2.png)

**Comment by ggctseng** [comment]
Apparently, according to this thread the FileVault Prebooter entry is normal:
https://www.tonymacx86.com/threads/clover-high-sierra-and-preboot.233308/

But not sure if the Boot macOS Install Prebooter is supposed to be there.

**Comment by P013onEr** [comment]
I met this problem after I upgrade S to HS , like this https://github.com/syscl/XPS9350-macOS/issues/171
and I also found @ZombieTheBest https://www.tonymacx86.com/threads/solved-kernel-panic-10-13-2-update-cant-even-install.241361/
BUT how to solve it ?

**Comment by rpruden** [comment]
You can hide the Preboot entries using your config.plist. The name of the entry you will want to hide will be called "Preboot" without the quotes. It's under the GUI tab in Clover Configuration Editor.

When I first finished my upgrade to HS, I was getting a boot loop. Some kernel panic and then a reboot. I was able to resolve it by changing my SMBIOS from 13,2 to 13,3. Give that a try. I also noticed that running the latest Deploy.sh seems to make my config.plist unreadable by clover configuration editor so I am not sure what is breaking that. Be sure that your config.plist isn't corrupted. You may need to generate a completely new SMBIOS using the 13,3 model type.

**Comment by ggctseng** [comment]
@rpruden My install is a completely new install and I haven't been able to get into High Sierra yet, but changing SMBIOS from 13,2 to 13,3 still results in boot loop.  I'm going to try and generate a new SMBIOS because I don't have anything in there right now.

**Comment by ggctseng** [comment]
Just as a note, I'm getting errors with Apple Keystore and apfs key bag so I'm not sure if it's something related to "security".  I formatted the drive with just APFS (not APFS encrypted).

**Comment by rpruden** [comment]
@ggctseng So you have prepped the USB (using current version of Clover and the Clover folder from the build on this repo), booted from it and ran the install. Install has completed but you have not been able to make it in to MacOS yet. Is that correct? Have you hit F4/FnF4 at the clover screen before trying to boot in to OSX?

Have you tried using Verbose and Safe Mode along with the 13,3 SMBIOS to get in to the install to ensure that it finished everything that it needed to finish? After my install was done, I would just get an Error icon if I tried to boot to it. After that, I just booted to clover, hit F4 then Fn+F4, waited a minute then adjusted the SMBIOS at the clover boot screen (Options Menu) and was able to get in. From there, I then installed clover to the SSD and created a new SMBIOS from Clover Configurator, then ran Deploy.sh.

I hope that you can find you way to the end on this.

**Comment by ggctseng** [comment]
@rpruden 

> So you have prepped the USB (using current version of Clover and the Clover folder from the build on this repo), booted from it and ran the install. Install has completed but you have not been able to make it in to MacOS yet. Is that correct? Have you hit F4/FnF4 at the clover screen before trying to boot in to OSX?

Yes and yes. I was able to boot into the install after just adding the Fix_Headers (see my 2nd post) and I believe install has completed because I've gone through the first and second reboots.  I just didn't know if I'm supposed to have "Boot macOS Install Prebooter from Preboot". Do you still have this entry?

> Have you tried using Verbose and Safe Mode along with the 13,3 SMBIOS to get in to the install to ensure that it finished everything that it needed to finish? After my install was done, I would just get an Error icon if I tried to boot to it. After that, I just booted to clover, hit F4 then Fn+F4, waited a minute then adjusted the SMBIOS at the clover boot screen (Options Menu) and was able to get in. From there, I then installed clover to the SSD and created a new SMBIOS from Clover Configurator, then ran Deploy.sh.

I haven't tried Safe Mode, but regular boot with the SMBIOS to 13,3 in config.plist still doesn't work.  I'll have to double-check and try adjusting SMBIOS using the clover boot screen.

So you didn't have any patched items in your APCI?

**Comment by ggctseng** [comment]
THIS IS THE SOLUTION REFERENCED IN MY FIRST POST

@rpruden Update. I am able to boot into High Sierra after I started with a minimal install of CLOVER using Rehabman's guide here:

https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

**_Note that this is not the clover configuration I used to install High Sierra, just to boot into it after I installed it using the CLOVER folder I attached above._**

For prosperity's sake I am attaching it here.
[CLOVER.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1645514/CLOVER.zip)

**First thing I did is get the laptop display working properly**
Interestingly, I noticed I had a lot of artifacts because I don't think I had the ig-platform-id set properly (it was 0x191b0000 by default from Rehabman's config.plist repository but I see it is 0x19260004 in ZombieTheBest's config.plist).  Regardless, I was able to connect my Dell U3818DW monitor to USB-C and it was able to use both displays at full resolution (without the artifacts on the internal display).  I installed the supplemental 10.13.2 update, rebooted and then the laptop display wouldn't work (it just ended at the last printout of the verbose boot log).  However, I was able to plug the my U3818DW and the picture showed up there (so maybe one way to debug your screen is to have an external monitor handy).  Once I changed the ig-platform-id to 0x19260004. The laptop and U3818DW seem to work--and the display hot plugs!  Not sure if USB works though...

Now the real work begins to start getting everything to work.

**Comment by rpruden** [comment]
@ggctseng Fantastic! I am so glad that you got it up and running. These things can be a white rabbit chase sometimes. I am going to check that ig-platform-id setting on mine, because ever since I switched to High Sierra, I have been unable to use my external monitor. I'm using a Dell P2715Q and I'm only making it work via a crappy USB adapter right now. I would really love to get DisplayPort via USB-C working again. Just to confirm, your USB-C DisplayPort connection works even if you weren't plugged in at boot?

To answer your earlier question, yes I still have the reboot to FileVault and the Reboot to install entries. They never went away so I just hid them in clover.

**Comment by ggctseng** [comment]
@rpruden It seems totally random sometimes, though I've learned from my previous Hackintosh experience (don't know how relevant this is now because that was back in Yosemite and Clover was catching on) that sometimes it was because I didn't rebuild my cache while other times I didn't save something where I thought I did.  

Re: USB-C. Yes, I have been able to plug in the monitor after boot (to clarify, the config.plist is NOT the one modified by deploy.sh but it's the bare minimum one I used to finally boot into the installer, which I attached to the posts a couple of posts above).  I note that the U3818DW has a USB-C port (provides PD so charges laptop too, so awesome) so that is what is directly hooked up  to the laptop--not being familiar with the DP standard yet, not sure if the display signals are going over as DP or USB-C.  The one quirk I've noticed so far is that randomly the screen will black out for a few seconds, then come back on.  The U3818DW has a USB 3.0 hub that's assignable to USB-C too, but I haven't been able to test whether the hub is recognized by the laptop.

**Comment by ggctseng** [comment]
@rpruden I'm slowly adding in patches, etc. to enable features, but I'm presuming you have the configuration I do (QHD, i7, sk Hynix pc300 SDD).  Would you mind sharing your config.plist and current Clover folder-with your SMBIOS info and ACPI folders removed, of course?

**Comment by aizigao** [comment]
same problem after upgrade from 10.12.6, mark

**Comment by ggctseng** [comment]
@aizigao Are you referencing the booting issue?  You can try the Clover that I put a few posts up.  Backup your current clover completely...

**Comment by aizigao** [comment]
@ggctseng 
> @aizigao Are you referencing the booting issue? You can try the Clover that I put a few posts up. Backup your current clover completely...

I use you clover and enter system, but screen is break 
![img_1431 2](https://user-images.githubusercontent.com/14126445/35179717-b915a8ee-fdda-11e7-83ea-0be6d4353fb8.JPG)
what is next step to do, should I run ./Deploy to fix it?

**Comment by aizigao** [comment]
@ggctseng My machine use 0x19260004 is work great, 👍

**Comment by ggctseng** [comment]
Yeah. I forgot to put that into the config.plist.  Now it's patching and etc. for you.

**Comment by rpruden** [comment]
@ggctseng 

> not sure if the display signals are going over as DP or USB-C. The one quirk I've noticed so far is that randomly the screen will black out for a few seconds, then come back on.

That screen flicker is something I have seen a lot with DisplayPort. I would be willing to bet you are sending DisplayPort over USB-C. If you click Apple > About this Mac > System Report > Graphics/Displays I believe it will tell you if you are using Display port. Mine is blank because I am using USB adapters right now though.

I will upload a copy of my clover folder and config.plist. I think we are using the same model. (QHD, i7, but with a replaced NVMe Toshiba SSD) Perhaps you will be able to help me fix it.

**Comment by rpruden** [comment]
@ggctseng Attached is my CLOVER folder along with my config.plist. I removed the serials from the SMBIOS.

[CLOVER.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1653168/CLOVER.zip)

**Comment by ggctseng** [comment]
@rpruden I think we should move the discussion to the other thread you created and I can mark this as solved, but one last note is that, yes, the U3818DW is sending DP over USB-C as confirmed using System Report.

**Comment by rishabhkjain** [comment]
@ggctseng were you able to get audio working with your system? I am able to get the speakers to work but my headphones have a lot of distortion.

**Comment by ggctseng** [comment]
@rishabhkjain I actually never tried the head phones. I'm currently back to an unpatched system as I am going to try and start from scratch but using deploy.sh as a guide as to what I should do.

If you haven't done so, go to tonymac and search.  I think I saw that issue being addressed.

**Comment by rishabhkjain** [comment]
@ggctseng I tried looking online and applying the patches but they did not work

also, if possible, can you document/list the patches that you apply for future reference

**Comment by ggctseng** [comment]
@rishabhkjain Will do re: patches.  You may want to try and ask for help on that tonymac site, but read the FAQ's first:
https://www.tonymacx86.com/forums/high-sierra-laptop-support.192/

**Comment by rishabhkjain** [comment]
@ggctseng I'll check tonymac this weekend when I have more time, thanks for the help! Let me know if you need anything from me.

**Comment by ggctseng** [comment]
@rishabhkjain What did you have to do to get the brightness keys to work. I got the slider working following the guide that you suggested:
https://tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightinjector-kext.218222/
