### ISSUE TITLE
Deploy.sh Errors

### ISSUE THREAD

**Issue by rpruden** [ZombieTheBest/XPS9350-10.13-HighSierra#24]
I am getting the below errors when running Deploy.sh. Are these normal or is there something I can do to fix these? There are. two that say failed and the rest of these are path issues it seems. Any thoughts?

-----output below-----

[ ---> ]  Updating files from https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra...
Already up-to-date.
[ Note ]  Your laptop is Iris version(i7-6560U).
[  OK  ]  Pre stage cleanup.
[  OK  ]  Create ./DSDT.
[  OK  ]  Create ./DSDT/prepare.
[  OK  ]  Create ./DSDT/precompile.
[  OK  ]  Create ./DSDT/compile.
.
.
.
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-7x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-7x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-8x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-8x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-9x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-9x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-10x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-10x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-11x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-11x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-12x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-12x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-13x* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-13x.aml: No such file or directory
mv: rename /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-14* to /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-14.aml: No such file or directory
[  OK  ]  SSDTs successfully renamed..
.
. --all ok between here--
.
[  OK  ]  Compiling DSDT.
[FAILED]  Compile DptfTa.
Error    6092 - Could not open file "/Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/precompile/.dsl" (Source Input) - No such file or directory

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

[  OK  ]  Compile SaSsdt.
.
. --all ok between here too--
.
[  OK  ]  Install Xhci table.
[FAILED]  Clean dynamic SSDTs.
rm: /Users/admin/Desktop/2018XPS9350/XPS9350-10.13-HighSierra/DSDT/compile/SSDT-*x.aml: No such file or directory
[  OK  ]  Drop SSDT-3.
.
.
. --everything after this is ok too

**Comment by hgh741** [comment]
@rpruden Is this problem solved？
I also met this problem。。。

**Comment by rpruden** [comment]
I have not been able to figure out the cause of these errors yet. I'm hoping someone else will have some insight.

**Comment by mircoianese** [comment]
Hi, sorry for the late reply. Ignore those errors please. That patch is supposed to rename SSDTs in case they are not already correctly renamed (this happens if you are using the original Clover). 
This REPO now includes Rehabman's Clover, which already renames the SSDTs correctly. So those errors are saying "can't rename the file as doesn't exists" (because is already renamed).

So, don't worry! No problem with that! :)

**Comment by rpruden** [comment]
Ah yes! Thank you for the feedback. I am glad to know this is not an issue.
