### ISSUE TITLE
complete DSDT.dsl and SSDT-1.dsl errors

### ISSUE THREAD

**Issue by hgh741** [ZombieTheBest/XPS9350-10.13-HighSierra#26]
@ZombieTheBest  hi, I run the  ./Deploy.sh -d , the log show complete DSDT.dsl and SSDT-1.dsl errors. How to fix it ?

**1. DSDT.dsl error:**
patch complete: 8 patches, 8 changes, 0 rejects
patched result written to '/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl'

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl   4026:                     Method (XDSM, 4, Serialized)  // _DSM: Device-Specific Method
Warning  3115 -                                                       Not all control paths return a value ^  (XDSM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  11172:                 Store (STSX, Local3)
Warning  3144 -                                                            Method Local is set but never used ^  (Local3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  11275:         Method (THDS, 1, Serialized)
Warning  3115 -                                           Not all control paths return a value ^  (THDS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12384:             Store (DAT1, Local1)
Warning  3144 -                                                        Method Local is set but never used ^  (Local1)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12556:             Method (GPEH, 0, NotSerialized)
Warning  3115 -                                               Not all control paths return a value ^  (GPEH)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12669:             Method (GPEH, 0, NotSerialized)
Warning  3115 -                                               Not all control paths return a value ^  (GPEH)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12718:             Method (_PS0, 0, Serialized)  // _PS0: Power State 0
Warning  3115 -                                               Not all control paths return a value ^  (_PS0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12728:                 Store (D0D3, Local3)
Warning  3144 -                                                            Method Local is set but never used ^  (Local3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12759:             Method (_PS3, 0, Serialized)  // _PS3: Power State 3
Warning  3115 -                                               Not all control paths return a value ^  (_PS3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12813:                 Method (_PS0, 0, Serialized)  // _PS0: Power State 0
Warning  3115 -                                                   Not all control paths return a value ^  (_PS0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12826:                 Method (_PS2, 0, Serialized)  // _PS2: Power State 2
Warning  3115 -                                                   Not all control paths return a value ^  (_PS2)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  12839:                 Method (_PS3, 0, Serialized)  // _PS3: Power State 3
Warning  3115 -                                                   Not all control paths return a value ^  (_PS3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13067:                         Method (SPPS, 2, Serialized)
Warning  3115 -                                                           Not all control paths return a value ^  (SPPS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13250:             Method (GPEH, 0, NotSerialized)
Warning  3115 -                                               Not all control paths return a value ^  (GPEH)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13295:             Method (GPEH, 0, NotSerialized)
Warning  3115 -                                               Not all control paths return a value ^  (GPEH)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13365:             Method (XDSM, 4, Serialized)  // _DSM: Device-Specific Method
Warning  3115 -                                               Not all control paths return a value ^  (XDSM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13528:             Method (RDCA, 5, Serialized)
Warning  3115 -                                               Not all control paths return a value ^  (RDCA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13636:                 Method (CNRS, 0, Serialized)
Warning  3115 -                                                   Not all control paths return a value ^  (CNRS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13670:                         While (LEqual (And (RDCA (NCRN, 0x52, Zero, Zero, Zero), 0x2000), Zero))
Warning  3122 -                                                                Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13688:                 Method (_PS3, 0, Serialized)  // _PS3: Power State 3
Warning  3115 -                                                   Not all control paths return a value ^  (_PS3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13695:                     Store (RDCA (NCRN, 0x04, Zero, Zero, 0x02), PCMD)
Warning  3122 -                                               Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13699:                         Store (RDCA (NCRN, 0x24, Zero, Zero, 0x02), PRBD)
Warning  3122 -                                                   Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13704:                         Store (RDCA (NCRN, 0x10, Zero, Zero, 0x02), PRBD)
Warning  3122 -                                                   Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13711:                 Method (_PS0, 0, Serialized)  // _PS0: Power State 0
Warning  3115 -                                                   Not all control paths return a value ^  (_PS0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13720:                     Store (RDCA (NCRN, Add (NPMV, 0x04), Zero, Zero, 0x02), Local0)
Warning  3122 -                                               Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13782:                 Method (CNRS, 0, Serialized)
Warning  3115 -                                                   Not all control paths return a value ^  (CNRS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13816:                         While (LEqual (And (RDCA (NCRN, 0x52, Zero, Zero, Zero), 0x2000), Zero))
Warning  3122 -                                                                Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13834:                 Method (_PS3, 0, Serialized)  // _PS3: Power State 3
Warning  3115 -                                                   Not all control paths return a value ^  (_PS3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13841:                     Store (RDCA (NCRN, 0x04, Zero, Zero, 0x02), PCMD)
Warning  3122 -                                               Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13845:                         Store (RDCA (NCRN, 0x24, Zero, Zero, 0x02), PRBD)
Warning  3122 -                                                   Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13850:                         Store (RDCA (NCRN, 0x10, Zero, Zero, 0x02), PRBD)
Warning  3122 -                                                   Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13857:                 Method (_PS0, 0, Serialized)  // _PS0: Power State 0
Warning  3115 -                                                   Not all control paths return a value ^  (_PS0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13866:                     Store (RDCA (NCRN, Add (NPMV, 0x04), Zero, Zero, 0x02), Local0)
Warning  3122 -                                               Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13928:                 Method (CNRS, 0, Serialized)
Warning  3115 -                                                   Not all control paths return a value ^  (CNRS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13962:                         While (LEqual (And (RDCA (NCRN, 0x52, Zero, Zero, Zero), 0x2000), Zero))
Warning  3122 -                                                                Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13980:                 Method (_PS3, 0, Serialized)  // _PS3: Power State 3
Warning  3115 -                                                   Not all control paths return a value ^  (_PS3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13987:                     Store (RDCA (NCRN, 0x04, Zero, Zero, 0x02), PCMD)
Warning  3122 -                                               Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13991:                         Store (RDCA (NCRN, 0x24, Zero, Zero, 0x02), PRBD)
Warning  3122 -                                                   Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  13996:                         Store (RDCA (NCRN, 0x10, Zero, Zero, 0x02), PRBD)
Warning  3122 -                                                   Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14003:                 Method (_PS0, 0, Serialized)  // _PS0: Power State 0
Warning  3115 -                                                   Not all control paths return a value ^  (_PS0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14012:                     Store (RDCA (NCRN, Add (NPMV, 0x04), Zero, Zero, 0x02), Local0)
Warning  3122 -                                               Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14126:             Store (PMEC, Local0)
Warning  3144 -                                                        Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14138:             Store (PMEC, Local0)
Warning  3144 -                                                        Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14357:         Device (I2C0)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14418:         Device (I2C1)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14479:         Device (I2C2)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14540:         Device (I2C3)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14601:         Device (I2C4)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14662:         Device (I2C5)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14723:         Device (SPI0)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14783:         Device (SPI1)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14843:         Device (UA00)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  14923:         Device (UA01)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  15003:         Device (UA02)
Warning  3141 -                                                             Missing dependency ^  (Device object requires a _HID or _ADR in same scope)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  15172:             Method (_INI, 0, NotSerialized)  // _INI: Initialize
Warning  3115 -                                               Not all control paths return a value ^  (_INI)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  15278:             Method (_INI, 0, NotSerialized)  // _INI: Initialize
Warning  3115 -                                               Not all control paths return a value ^  (_INI)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  15375:             Method (_INI, 0, NotSerialized)  // _INI: Initialize
Warning  3115 -                                               Not all control paths return a value ^  (_INI)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  15474:             Method (_INI, 0, NotSerialized)  // _INI: Initialize
Warning  3115 -                                               Not all control paths return a value ^  (_INI)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16308:                 Store (CLR, Local0)
Warning  3144 -                                                           Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16413:                 Store (D0D3, Local0)
Warning  3144 -                                                            Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16426:                 Store (D0D3, Local0)
Warning  3144 -                                                            Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16585:                     Store (PSTA, Local0)
Warning  3144 -                                                                Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16592:                     Store (PSTA, Local0)
Warning  3144 -                                                                Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16595:                 Method (XDSM, 4, Serialized)  // _DSM: Device-Specific Method
Warning  3115 -                                                   Not all control paths return a value ^  (XDSM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16691:                     Store (PSTA, Local0)
Warning  3144 -                                                                Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16698:                     Store (PSTA, Local0)
Warning  3144 -                                                                Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16701:                 Method (XDSM, 4, Serialized)  // _DSM: Device-Specific Method
Warning  3115 -                                                   Not all control paths return a value ^  (XDSM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  16768:             Method (XDSM, 4, NotSerialized)  // _DSM: Device-Specific Method
Warning  3115 -                                               Not all control paths return a value ^  (XDSM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  17022:         Add (One, ShiftLeft (Local2, One, Local2), Local3)
Warning  3144 -                                                                                  Method Local is set but never used ^  (Local3)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  17545:     Method (SPL1, 0, Serialized)
Warning  3115 -                                       Not all control paths return a value ^  (SPL1)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  17583:     Method (GUAM, 1, Serialized)
Warning  3115 -                                       Not all control paths return a value ^  (GUAM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  17751:             If (CondRefOf (\_OSI, Local0))
Warning  3144 -                                                                 Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  18511:             Store (\_SB.STDC (\_SB.PCI0.GPCB (), Zero, TBTD (TBSE), TBTF (TBSE), 0x05), Local7)
Warning  3122 -                                            Called method may not always return a value ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  18692:         Method (_E42, 0, NotSerialized)  // _Exx: Edge-Triggered GPE
Warning  3115 -                                           Not all control paths return a value ^  (_E42)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  18981:         Method (STDC, 5, Serialized)
Warning  3115 -                                           Not all control paths return a value ^  (STDC)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  19474:                 Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                    Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  19803:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  20131:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  20459:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  20789:                 Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                    Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  21118:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  21446:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  21774:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  21941:         Scope (_SB.PCI0.RP09.PXSX)
Error    6085 -                                               Object not found or not accessible from scope ^  (_SB.PCI0.RP09.PXSX)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  21941:         Scope (_SB.PCI0.RP09.PXSX)
Error    6116 -                                          Forward references from Scope operator not allowed ^  (_SB.PCI0.RP09.PXSX)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  22104:                 Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                    Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  22433:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  22761:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  23089:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  23417:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  23745:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  24073:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  24401:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  24729:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  25057:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  25385:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  25713:             Method (_STA, 0, NotSerialized)  // _STA: Status
Warning  3107 -                                                Reserved method must return a value ^  (Integer required for _STA)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  28845:                                 If (LOr (^^PCI0.RP09.SSD0.PAHC (), ^^PCI0.RP09.SSD0.PNVM ()))
Error    6085 -                                                                            Object not found or not accessible from scope ^  (^^PCI0.RP09.SSD0.PAHC)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  28845:                                 If (LOr (^^PCI0.RP09.SSD0.PAHC (), ^^PCI0.RP09.SSD0.PNVM ()))
Error    6085 -                                                                                                      Object not found or not accessible from scope ^  (^^PCI0.RP09.SSD0.PNVM)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  29062:                                 If (^^PCI0.RP09.SSD0.WIST ())
Error    6085 -                                                                       Object not found or not accessible from scope ^  (^^PCI0.RP09.SSD0.WIST)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  30357:         Method (_CRS, 0, Serialized)  // _CRS: Current Resource Settings
Warning  3115 -                                           Not all control paths return a value ^  (_CRS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  30357:         Method (_CRS, 0, Serialized)  // _CRS: Current Resource Settings
Warning  3107 -                                            Reserved method must return a value ^  (Buffer required for _CRS)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  31018:             Divide (Arg2, 0x04, Local3, Local4)
Warning  3144 -                                                                       Method Local is set but never used ^  (Local4)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  31439:                 If (CondRefOf (\_OSI, Local0))
Warning  3144 -                                                                     Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  31542:                 Store (DCLS, Local1)
Warning  3144 -                                                            Method Local is set but never used ^  (Local1)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  31546:                     Store (^^^LID0._LID (), Local0)
Warning  3144 -                                                                           Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  32289:                 Acquire (PATM, 0x0064)
Warning  3130 -                                    Result is not used, possible operator timeout will be missed ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  32986:             Divide (Local0, 0x64, Local5, Local3)
Warning  3144 -                                                                 Method Local is set but never used ^  (Local5)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  33860:                     Store (ECGC (), Local0)
Warning  3144 -                                                                   Method Local is set but never used ^  (Local0)

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl  34155:                     If (And (Local0, One, Local1))
Warning  3144 -                                                                         Method Local is set but never used ^  (Local1)

ASL Input:     /Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/DSDT.dsl - 34292 lines, 1058092 bytes, 16579 keywords

Compilation complete. 5 Errors, 105 Warnings, 180 Remarks, 238 Optimizations, 2 Constants Folded
[ Note ]  syscl_SSD was not applied as it was causing errors..

**2. SSDT-1.dsl errors**
patch complete: 2 patches, 1 changes, 0 rejects
patched result written to '/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl'

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160422-64(RM)
Copyright (c) 2000 - 2016 Intel Corporation

Compiler aborting due to parser-detected syntax error(s)
/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl    101:                                 }
Error    6126 -                                                                  syntax error, unexpected '}' ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl    122:                                 If (LGreater (DFUD, Zero))
Error    6126 -                                                            syntax error, unexpected PARSEOP_IF ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl    123:                                 {
Error    6126 -                                                                  syntax error, unexpected '{' ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl    127:                                 }
Error    6126 -                                                                  syntax error, unexpected '}' ^ 

/Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl    157: 
Error    6126 - syntax error, unexpected $end and premature End-Of-File

ASL Input:     /Users/hugowong/Documents/XPS9350-10.13-HighSierra/DSDT/raw/SSDT-1.dsl - 157 lines, 6080 bytes, 77 keywords

Compilation complete. 5 Errors, 0 Warnings, 0 Remarks, 0 Optimizations
[ Note ]  rename_DSM was not applied as it was causing errors..

This is my ACPI/origin :
[origin.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1658161/origin.zip)

**Comment by nickawilliams** [comment]
I'm also getting the same 5 errors, though I'm currently working from @syscl's Deploy.sh. Probably the same issue, but I don't know enough about these ACPI tables to understand what the issue is (beyond the fact that it seems to be SSD related).

**Comment by mircoianese** [comment]
SSDTs can be removed. Leave only DSDT.aml and other extra AML files. Remove
SortedOrders from config.plist and DropOem option.

Just use Generate/PluginType=true.

Let me know!

Il Mer 24 Gen 2018, 02:20 hgh741 <notifications@github.com> ha scritto:
