### ISSUE TITLE
Mojave Support?

### ISSUE THREAD

**Issue by tlefko** [ZombieTheBest/XPS9350-10.13-HighSierra#29]
Hello, hope all is well. I know this is written for High Sierra, but is there a chance this would work on Mojave? I did some research and see that I would need to do audio myself patched, but would the rest work?

If not, is there a chance of it happening any development on your part for it? Any feedback would be appreciated!

Thanks

**Comment by ltesla** [comment]
some question,hoping to get update soon. Cheers!

**Comment by mircoianese** [comment]
Hello! Sorry for the late response.

Unfortunately I do not own this laptop anymore, so from my point there will be no updates anymore for this project.

These patches will certainly not work on Mojave, but feel free to fork and fix issues on new OS! :)
