### ISSUE TITLE
Backlight Issue

### ISSUE THREAD

**Issue by chenyisen** [ZombieTheBest/XPS9350-10.13-HighSierra#3]
Hello, Zombiethebest. The clipboard works perfect, thank you! Handoff works sometimes, but that's necessary for me.
I found that I can't change the backlight of my monitor, and there are no options to adjust backlight in setting, and the function is normal in 10.12.
Could you find a way to rescue my backlight? Thank you.
Here is my clover folder.

[CLOVER.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1424935/CLOVER.zip)

**Comment by ZombieTheBest** [comment]
Please try to put the attached SSDT-PNLF.aml in Clover/ACPI/patched and then add it on SortedOrder in your config.plist. 
Let me know if this fix your backlight issue! Thank you 

[SSDT-PNLF.aml.zip](https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/files/1424945/SSDT-PNLF.aml.zip)

**Comment by chenyisen** [comment]
Perfect! It works. Maybe you could update the dsdt folder. Thanks!

**Comment by ZombieTheBest** [comment]
Nice! Will update the Script ASAP! Thank you for your feedback!

Il 29 Ott 2017 12:47, "chenyisen" <notifications@github.com> ha scritto:

**Comment by ZombieTheBest** [comment]
Fixed Deploy. Thank you again for your feedback!

**Comment by ZombieTheBest** [comment]
@chenyisen Regarding Handoff issue, please try this:

1. Go to `System/Library/Extensions`
2. You Should have a file called `AirPortBrcmNIC-MFG.bak, rename it to `AirPortBrcmNIC-MFG.kext`
3. Rebuild cache: `sudo touch /System/Library/Extensions && sudo kextcache -i /`
4. Reboot and see if something changes between having the kext activated or not (in my case it was broking my BT). 

Thank you!

**Comment by ZombieTheBest** [comment]
@chenyisen Please try the BETA release if you can: https://github.com/ZombieTheBest/XPS9350-10.13-HighSierra/issues/6
