### ISSUE TITLE
Which Clover version should I use?

### ISSUE THREAD

**Issue by jerryzj** [ZombieTheBest/XPS9350-10.13-HighSierra#4]
Hallo

As title, I see the latest clover version is r4268. I'm curious is there any restriction on the Clover version ?

Thanks, 
Jerry

**Comment by ZombieTheBest** [comment]
Hello! No, there isn't, it just have to support apfs using apfs.efi. I will
update clover version later this day! Thank you very much!

Il 30 Ott 2017 04:15, "Jerry ZJ" <notifications@github.com> ha scritto:

**Comment by dgrah50** [comment]
When following the guide and installing clover on the installation disk, once I reboot and launch from the installation disk the option to start the macos installer is not present. The options are EFI shell, shutdown reboot etc. Why is this? Is this due to the Clover version I am using?
