### ISSUE TITLE
Unable to install High Sierra

### ISSUE THREAD

**Issue by vinv** [ZombieTheBest/XPS9350-10.13-HighSierra#7]
Hello,

Started my own issue as discussed. Since my last report, I created a new HS USB installer, installed Clover on it, then copied over your CLOVER folder and booted from it. I was able to do 2 stages(?) of the install - about 10mins, then a reboot, then another 10mins. Then when the installer reboots again to "complete install", there is a kernel panic. Sorry I'm sketchy on details (I enabled -v and Don't reboot after install, but the panic dumps a lot of data and I don't know how to scroll back up to see what module/driver panicked in the first place).

I also had another basic question. In your (and syscl's) instructions, when are supposed to execute steps 7 and 8? The installer reboots multiple times, should we wait to come to desktop before installing clover onto the SSD or boot into USB and do it from there (somehow). I waited until the complete install sections were done and we were in the desktop before installing clover onto the SSD for the Sierra install and that worked, but the last step does not occur with HS.

**Comment by ZombieTheBest** [comment]
@vinv Regarding Clover and all the rest: yes, you have to wait until you reach the Desktop.

Please attach a picture of what you see on screen when it crashes

**Comment by vinv** [comment]
Hi, not sure what you can tell, but here it is - 
![img_4324](https://user-images.githubusercontent.com/10717152/32245557-b3de3590-be41-11e7-9a6e-e8243d30ba58.JPG)

**Comment by ZombieTheBest** [comment]
FixHeaders_20000000 is true in your config.plist I suppose, right? Bootargs darkwake=0? Try also to remove all kexts except as VoodooPS2 and FakeSMC from CLOVER/kexts
