### ISSUE TITLE
No progression bar after booting into High Sierra from Clover bootloader

### ISSUE THREAD

**Issue by mingiryu** [ZombieTheBest/XPS9350-10.13-HighSierra#8]
I have been on Sierra with 2016 XPS9350 i3 and DW1560. I have been unable to go past the apple logo screen after booting into Clover. The progression bar never shows up and I'm just stuck with the apple logo screen. I've used the same method I used for installing Sierra except the fact that I used your Clover folder.

**Comment by ZombieTheBest** [comment]
Boot with -v arg and post a picture of the output. Thanks

**Comment by mingiryu** [comment]
![img_0013](https://user-images.githubusercontent.com/12177666/32929479-ea2556f4-cb1d-11e7-8fad-9830e08d2d72.PNG)
![img_0014](https://user-images.githubusercontent.com/12177666/32929480-ea3a9c12-cb1d-11e7-8855-cec90b9297dd.PNG)
![img_0015](https://user-images.githubusercontent.com/12177666/32929481-ea5252d0-cb1d-11e7-8d9f-eb64eb5cc453.PNG)
![img_0016](https://user-images.githubusercontent.com/12177666/32929482-ea627f52-cb1d-11e7-9a4f-46c10b26bf4b.PNG)
![img_0017](https://user-images.githubusercontent.com/12177666/32929483-ea74b7c6-cb1d-11e7-81d5-f0377403900e.PNG)

**Comment by ZombieTheBest** [comment]
Post your Clover Folder Please

**Comment by mingiryu** [comment]
@ZombieTheBest I used the beta version of your clover folder.

**Comment by P013onEr** [comment]
@mingiryu add FixHeaders=true in your config.list

**Comment by mingiryu** [comment]
@P013onEr I still have the same issue.
[config.plist](https://gist.github.com/mingiryu/3547b6bb6e9fefe966558a5b90b4e145)

**Comment by maz-1** [comment]
![screenshot](https://user-images.githubusercontent.com/5277060/34155248-87f42038-e4f3-11e7-84c6-5dbfd04ac998.png)
Try these two settings in ACPI section.

**Comment by mingiryu** [comment]
@maz-1 Thank you! It fixed the issue.

**Comment by maz-1** [comment]
I'm sorry that I made a mistake.
The DSDT patch is not necessary, Drop BGRT table is enough.
