### ISSUE TITLE
thunderbolt 3 patch need to be updated for high sierra

### ISSUE THREAD

**Issue by maz-1** [ZombieTheBest/XPS9350-10.13-HighSierra#9]
this patch no longer works on high sierra

			<dict>  

				<key>Comment</key>  

				<string>Bypass ThunderBolt3 SkipEnumeration credit kid2010 implemented by syscl</string>  

				<key>Disabled</key>  

				<false/>  

				<key>Find</key>  

				<data>

				VUiJ5UFXQVZBVUFUU0iB7DgB

				</data>

				<key>Name</key>

				<string>IOThunderboltFamily</string>

				<key>Replace</key>

				<data>

				VUiJ5THAXcNBVUFUU0iB7DgB

				</data>

			</dict>
`

**Comment by maz-1** [comment]
Is this patch responsible for a working thunderbolt port?

**Comment by rpruden** [comment]
@maz-1 This was closed, was there a resolution for this?

**Comment by maz-1** [comment]
@rpruden
This patch has nothing to do with xps13 type-c issue, it is a more generic issue for all PCs with macOS.
